name: build-and-test
on: [pull_request]
jobs:
  build-and-test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
      - name: Build Rust
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Build Wasm
        run: |
          cargo install wasm-pack
          wasm-pack build --target nodejs --release
      - name: use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          cd www
          npm install
          npm test
